dist: xenial
language: c

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev
    - libboost-dev
    - libgmp-dev:i386
    - libreadline-dev:i386
    - zlib1g-dev:i386
    - libboost-dev:i386
    - gcc-multilib
    - g++-multilib

matrix:
  include:
    - env: GAPBRANCH=master
    - env: GAPBRANCH=stable-4.10
    - env: GAPBRANCH=stable-4.9
    - env: GAPBRANCH=master ABI=32
    - env: GAPBRANCH=stable-4.10 ABI=32
    - env: GAPBRANCH=stable-4.9 ABI=32

branches:
  only:
    - master

before_script:
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
  - ./build-normaliz.sh $HOME/gap
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
  - make doc
after_script:
  - scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
